# Folder that contains all the data generated by the scripts
data_folder = "data/"
# Path to store temporarily all updated and new files
temp_folder = "temp_updt/"

# updt_ucc paths
# Path to the file that contains the NASA API token
NASA_API_TOKEN_file = data_folder + "NASA_API_TOKEN"
# Root of CSV file with merged DBs
merged_dbs_file = "DBs_merged.csv"
# Root of CSV file with final UCC catalogue
ucc_cat_file = "UCC_cat_"
# Path to the DBs
dbs_folder = data_folder + "databases/"
# Path to the JSON file with DBs data
name_DBs_json = data_folder + "databases_info.json"
# Path to the database of GCs
GCs_cat = data_folder + "globulars.csv"
# Path to the file with manual OC parameters
manual_pars_file = data_folder + "manual_params.csv"
# Preferred order in which the OCs are assigned their primary name
naming_order = (
    "hyades",
    "blanco",
    "westerlund",
    "ngc",
    "melotte",
    "trumpler",
    "ruprecht",
    "berkeley",
    "pismis",
    "vdbh",
    "loden",
    "kronberger",
    "collinder",
    "haffner",
    "tombaugh",
    "dolidze",
    "auner",
    "waterloo",
    "basel",
    "bochum",
    "hogg",
    "carraro",
    "lynga",
    "johansson",
    "mamajek",
    "platais",
    "harvard",
    "czernik",
    "koposov",
    "eso",
    "ascc",
    "alessiteutsch",
    "teutsch",
    "alessi",
    "king",
    "saurer",
    "fsr",
    "juchert",
    "antalova",
    "stephenson",
    "messineo1",
    "patchick90",
    "sai",
    "coingaia",
    "gulliver",
    "dutrabica",
    "ubc",
    "feigelson1",
)

# The B script uses the first available coordinates for the entries, except
# those from KHARCHENKO2012 which are always ignored by default. These entries
# have bad coordinates in their first appearances, so we fix them here
selected_center_coords = {
    "ascc72": (193.741, -60.949),  # BICA2019
    "fsr0839": (91.013, 30.27),  # KHARCHENKO2012
    "dolidze50": (241.403, -20.485),  # KHARCHENKO2012
    "fsr0124": (286.733, 13.245),  # KHARCHENKO2012
    "loden995": (208.575, -64.95),  # KHARCHENKO2012
    "ruprecht53": (122.68, -26.94),  # KHARCHENKO2012
    "ngc7762": (357.465, 68.025),  # KHARCHENKO2012
    "ngc6664": (279.132, -8.21),  # KHARCHENKO2012
    "ngc2184": (91.69, -2.0),  # CANTAT2020
    "ruprecht19": (111.48, -21.844),  # CANTAT2020
    "ruprecht167": (215.15, -58.858),  # CANTAT2020
    "upk45": (291.696, 0.212),  # CANTAT2020
    "collinder471": (332.563, 73.032),  # HUNT2023
}


# Zenodo paths and names
#
# Path to the folder that stores the latest UCC version
zenodo_folder = data_folder + "zenodo/"
# Path to the folder that stores the archived UCC versions
UCC_archive = data_folder + "ucc_archived/"
# Name of the  file that contains all of the members
UCC_members_file = data_folder + "UCC_members.parquet"
# File that stores the dates and status of each member extraction
parquet_dates = data_folder + "data_dates.json"


# Paths to the Gaia DR3 files in external drive
#
# Path to the folder that contains the raw data
root = "/media/gabriel/backup/gabriel/GaiaDR3/"
# root = "/home/gperren.ifir/UCC/GaiaDR3/"
path_gaia_frames = root + "datafiles_G20/"
# Path to the file that informs the sky area covered by each raw data file
path_gaia_frames_ranges = root + "files_G20/frame_ranges.txt"
# Maximum magnitude to retrieve
gaia_max_mag = 20


# Path to local ASteCA version
local_asteca_path = "/home/gabriel/Github/ASteCA/ASteCA/asteca"
# local_asteca_path = "/home/gperren.ifir/asteca"

# Order used for the C3 classes
class_order = [
    "AA",
    "AB",
    "BA",
    "AC",
    "CA",
    "BB",
    "AD",
    "DA",
    "BC",
    "CB",
    "BD",
    "DB",
    "CC",
    "CD",
    "DC",
    "DD",
]


# UCC site paths
#
# Root path to the repo for the ucc site
ucc_path = "ucc/"
# Path to the md entries folder
md_folder = ucc_path + "_clusters/"
# Path to the pages folder
pages_folder = ucc_path + "_pages/"
# Path to the tables folders
tables_folder = ucc_path + "_tables/"
dbs_tables_folder = tables_folder + "dbs/"
# Path to the ucc site images folder
images_folder = ucc_path + "images/"
# Assets folder
assets_folder = ucc_path + "assets/"
# Path to the compressed CSV file with clusters data
clusters_csv_path = assets_folder + "clusters.csv.gz"
# Path to the md database file
databases_md_path = pages_folder + "DATABASE.md"
# Path to the md file with the articles
articles_md_path = pages_folder + "ARTICLES.md"
# Path to the md file with the tables
tables_md_path = pages_folder + "TABLES.md"

# Q folders paths and files
#
# Path to the .parquet member files
members_folder = "datafiles/"
# Path to the cluster's plots
plots_folder = "plots/"
plots_sub_folders = ("UCC", "aladin")  # , "HUNT23", "CANTAT20"
