# Folder that contains all the data generated by the scripts
data_folder = "data/"
# Path to store temporarily all updated and new files
temp_folder = "temp_updt/"

# updt_ucc paths
# Path to the file that contains the NASA API token
NASA_API_TOKEN_file = data_folder + "NASA_API_TOKEN"
# Root of CSV file with merged DBs
merged_dbs_file = "UCC_cat_B.csv"
# Root of CSV file with final UCC catalogue
ucc_cat_file = "UCC_cat_C.csv"
# Path to the DBs
dbs_folder = data_folder + "databases/"
# Path to the JSON file with DBs data
name_DBs_json = data_folder + "databases_info.json"
# Path to the database of GCs
GCs_cat = data_folder + "globulars.csv"
# Path to the file with manual OC parameters
manual_pars_file = data_folder + "manual_params.csv"
# Preferred order in which the OCs are assigned their primary name
naming_order = (
    "melotte",  # 1915
    "hyades",
    "trumpler",  # 1930
    "collinder",  # 1931
    "tombaugh",  # 1940
    "haffner",  # 1957
    "ruprecht",  # 1958
    "berkeley",  # 1958
    "pismis",  # 1959
    "basel",  # 1971
    "loden",  # 1973
    "vdbh",  # 1975
    "bochum",  # 1975
    "ngc",
)

# Exceptions to the rule below
selected_centers_f = data_folder + "manual_centers.csv"
# Hierarchy of databases for selecting coordinates, smaller is preferred
# Exceptions are stored in the file above.
DB_coords_hierarchy = {
    "CANTAT2020": 0,
    "HUNT2023": 1,
    "WEI2025": 900,
    "LOKTIN2017": 995,
    "KHARCHENKO2016": 996,
    "KHARCHENKO2013": 997,
    "KHARCHENKO2012": 998,
    "PISKUNOV2007": 998,
    "PISKUNOV2008": 998,
    "KHARCHENKO2007": 999,
    "KHARCHENKO2005": 999,
    "HE2022": 1000,
    "HE2022_1": 1000,
}


#
UCC_cmmts_folder = "json_cmmts/"
UCC_cmmts_file = "UCC_summ_cmmts.json.gz"


# Bad OCs parameters
UTI_max = 0.25
C_dup_min = 0.75
C_lit_max = 0.3


# Order used to store the fundamental parameters in the B database
fpars_order = (
    "dist",
    "ext",
    "diff_ext",
    "age",
    "met",
    "mass",
    "bi_frac",
    "blue_str",
)
# Used to generate the per OC fundamental parameters tables
# MUST MATCH the 'fpars_order' order beyond the second column
fpars_headers = (
    "Reference",
    "Year",
    "Dist [kpc]",
    "Av [mag]",
    "DAv [mag]",
    "Age [Myr]",
    "[Fe/H] [dex]",
    "Mass [Msun]",
    "B<sub>frac</sub>",
    "BSS",
)

# Coefficients to transform fundamental parameters
#
# Ag is always assumed to be Gaia's G band. The coefficient in Av=1.2*Ag
# comes from the sources:
# Jordi et al 2010; https://www.aanda.org/articles/aa/full_html/2010/15/aa15441-10/aa15441-10.html
# Wang & Chen 2019; https://iopscience.iop.org/article/10.3847/1538-4357/ab1c61

# Conversion from Evi is also taken from Wang & Chen 2019
c_z_sun = 0.0152
c_Ag = 1.2
c_Ebv = 3.1
c_Evi = 2.5


# Zenodo paths and names
#
# Path to the folder that stores the latest UCC version
zenodo_folder = data_folder + "zenodo/"
# Path to the folder that stores the archived UCC versions
# UCC_archive = data_folder + "ucc_archived/"
# Name of the  file that contains all of the members
UCC_members_file = "UCC_members.parquet"
# File that stores the dates and status of each member extraction
# parquet_dates = data_folder + "data_dates.json"
# Path to the temporary individual .parquet member files
temp_members_folder = temp_folder + "datafiles/"
# Final name of Zenodo catalogue
zenodo_cat_fname = "UCC_cat.csv"

# Paths to the Gaia DR3 files in external drive
#
# Path to the folder that contains the raw data
root = "/media/gabriel/backup/gabriel/GaiaDR3/"
# root = "/home/gperren.ifir/UCC/GaiaDR3/"
path_gaia_frames = root + "datafiles_G20/"
# Path to the file that informs the sky area covered by each raw data file
path_gaia_frames_ranges = root + "files_G20/frame_ranges.txt"
# Maximum magnitude to retrieve
gaia_max_mag = 20


# Path to local ASteCA version
local_asteca_path = "/home/gabriel/Github/ASteCA/ASteCA/asteca"
# local_asteca_path = "/home/gperren.ifir/asteca"

# Order used for the C3 classes
class_order = [
    "AA",
    "AB",
    "BA",
    "AC",
    "CA",
    "BB",
    "AD",
    "DA",
    "BC",
    "CB",
    "BD",
    "DB",
    "CC",
    "CD",
    "DC",
    "DD",
]


# UCC site paths
#
# Root path to the 'ucc/' folder
root_ucc_path = "../"
# Path to the repo for the ucc site
ucc_path = "ucc/"
# Path to the md entries folder
md_folder = ucc_path + "_clusters/"
# Path to the pages folder
pages_folder = ucc_path + "_pages/"
# Path to the tables folders
tables_folder = ucc_path + "_tables/"
dbs_tables_folder = tables_folder + "dbs/"
# Path to the ucc site images folder
images_folder = ucc_path + "images/"
# Assets folder
assets_folder = ucc_path + "assets/"
# Member files folder
members_files_folder = assets_folder + "members/"
# Path to the compressed CSV file with clusters data
clusters_csv_path = "clusters_*.csv.gz"
clusters_manifest_path = "clusters_manifest.json"
# Path to the md database file
databases_md_path = pages_folder + "DATABASE.md"
# Path to the md file with the articles
articles_md_path = pages_folder + "ARTICLES.md"
# Path to the md file with the tables
tables_md_path = pages_folder + "TABLES.md"

# Plots paths and files
#
# Path to the cluster's plots
plots_folder = "plots/"
plots_sub_folders = ("UCC", "aladin", "gcpos")  # , "HUNT23", "CANTAT20"
# This is a modified style that removes the Latex dependence from 'scienceplots'
custom_style_path = "modules/E_funcs/science2.mplstyle"


# New spiral arms
# https://www.aanda.org/articles/aa/full_html/2021/08/aa39751-20/aa39751-20.html

# Momany et al. (2006) "Outer structure of the..."
spiral_arms = {
    "Outer": (
        (7.559999999999999, 2.514124293785308),
        (7.237333333333332, 3.4180790960452008),
        (6.738666666666667, 4.46327683615819),
        (6.1519999999999975, 5.480225988700564),
        (5.535999999999998, 6.384180790960453),
        (4.861333333333334, 7.1186440677966125),
        (4.479999999999997, 7.514124293785311),
        (3.8053333333333335, 7.909604519774014),
        (2.8373333333333335, 8.474576271186443),
        (1.751999999999999, 9.011299435028253),
        (0.6373333333333306, 9.35028248587571),
        (-0.4480000000000022, 9.63276836158192),
        (-1.2693333333333356, 9.830508474576273),
        (-1.8560000000000016, 9.943502824858761),
        (-2.677333333333337, 10),
        (-3.4986666666666686, 9.943502824858761),
        (-4.085333333333336, 9.915254237288138),
        (-5.024000000000003, 9.830508474576273),
        (-5.845333333333336, 9.689265536723166),
        (-6.4906666666666695, 9.519774011299436),
        (-7.253333333333337, 9.322033898305087),
        (-7.986666666666669, 8.926553672316388),
        (-8.485333333333337, 8.559322033898308),
        (-9.160000000000004, 8.050847457627121),
        (-9.864000000000004, 7.570621468926557),
        (-10.333333333333336, 7.203389830508474),
        (-10.89066666666667, 6.525423728813561),
        (-11.389333333333337, 5.9604519774011315),
        (-11.77066666666667, 5.395480225988699),
        (-12.240000000000004, 4.661016949152543),
        (-12.65066666666667, 3.9830508474576263),
        (-13.061333333333337, 3.361581920903955),
        (-13.442666666666671, 2.7401129943502838),
    ),
    "Perseus": (
        (5.2719999999999985, 2.372881355932204),
        (4.9786666666666655, 3.27683615819209),
        (4.773333333333333, 3.6723163841807924),
        (4.3039999999999985, 4.46327683615819),
        (3.776, 5.141242937853107),
        (3.3359999999999985, 5.593220338983052),
        (2.690666666666665, 6.073446327683616),
        (2.074666666666662, 6.468926553672318),
        (1.4879999999999995, 6.751412429378529),
        (0.607999999999997, 7.005649717514125),
        (-0.15466666666666917, 7.146892655367235),
        (-0.8293333333333344, 7.259887005649716),
        (-1.621333333333336, 7.316384180790962),
        (-2.4426666666666694, 7.288135593220339),
        (-3.14666666666667, 7.1186440677966125),
        (-3.909333333333336, 7.005649717514125),
        (-4.6426666666666705, 6.666666666666668),
        (-5.3173333333333375, 6.3559322033898304),
        (-5.962666666666669, 5.903954802259886),
        (-6.57866666666667, 5.395480225988699),
        (-6.989333333333336, 5.028248587570623),
        (-7.63466666666667, 4.350282485875709),
        (-8.104000000000003, 3.7570621468926575),
        (-8.51466666666667, 3.10734463276836),
        (-8.896000000000004, 2.4011299435028235),
        (-9.218666666666671, 1.6384180790960414),
        (-9.424000000000003, 1.073446327683616),
        (-9.65866666666667, 0.1977401129943459),
        (-9.805333333333337, -0.5084745762711869),
        (-9.92266666666667, -0.8192090395480243),
        (-10.010666666666669, -1.2711864406779654),
        (-10.128000000000004, -2.005649717514128),
        (-10.186666666666671, -2.711864406779661),
        (-10.186666666666671, -2.909604519774014),
        (-10.128000000000004, -3.3615819209039586),
        (-9.952000000000004, -4.2372881355932215),
        (-9.83466666666667, -5),
        (-9.688000000000002, -5.310734463276839),
        (-9.48266666666667, -5.734463276836161),
        (-9.189333333333337, -6.29943502824859),
        (-8.86666666666667, -7.005649717514126),
        (-8.456000000000003, -7.598870056497178),
    ),
    "Orion-Cygnus": (
        (-7.341333333333337, 3.2485875706214706),
        (-7.63466666666667, 2.909604519774014),
        (-7.9280000000000035, 2.485875706214692),
        (-8.280000000000003, 1.9209039548022595),
        (-8.456000000000003, 1.4124293785310726),
        (-8.60266666666667, 1.1016949152542352),
        (-8.808000000000003, 0.5649717514124291),
        (-9.013333333333335, -0.197740112994353),
        (-9.13066666666667, -0.7627118644067821),
        (-9.160000000000004, -1.2146892655367267),
    ),
    "Carina-Sagittarius": (
        (2.8373333333333335, 3.6723163841807924),
        (2.5146666666666633, 4.152542372881356),
        (2.338666666666665, 4.350282485875709),
        (1.9280000000000008, 4.774011299435031),
        (1.2239999999999966, 5.16949152542373),
        (0.49066666666666237, 5.451977401129945),
        (-0.12533333333333552, 5.593220338983052),
        (-0.7706666666666688, 5.621468926553675),
        (-1.7680000000000025, 5.53672316384181),
        (-2.5600000000000023, 5.310734463276834),
        (-2.970666666666668, 5.112994350282488),
        (-3.645333333333337, 4.576271186440678),
        (-3.8800000000000026, 4.350282485875709),
        (-4.2613333333333365, 3.9830508474576263),
        (-4.613333333333337, 3.5593220338983045),
        (-4.789333333333337, 3.192090395480225),
        (-5.1413333333333355, 2.627118644067796),
        (-5.493333333333336, 2.033898305084744),
        (-5.845333333333336, 1.4124293785310726),
        (-6.22666666666667, 0.6497175141242906),
        (-6.608000000000002, -0.14124293785311082),
        (-6.842666666666668, -0.7627118644067821),
        (-7.048000000000004, -1.5536723163841835),
        (-7.19466666666667, -2.25988700564972),
        (-7.253333333333337, -3.1073446327683634),
        (-7.136000000000003, -3.6440677966101696),
        (-7.048000000000004, -3.98305084745763),
        (-6.813333333333338, -4.519774011299436),
        (-6.461333333333336, -5.254237288135597),
        (-6.05066666666667, -5.875706214689268),
        (-5.6106666666666705, -6.440677966101699),
        (-5.024000000000003, -6.977401129943505),
        (-4.466666666666669, -7.485875706214692),
        (-3.8800000000000026, -7.909604519774014),
        (-3.352000000000002, -8.163841807909607),
        (-3.0880000000000027, -8.361581920903957),
    ),
    "Crux-Scutum": (
        (1.663999999999998, 3.1355932203389827),
        (1.3119999999999976, 3.4180790960452008),
        (0.6666666666666643, 3.8135593220338997),
        (-0.09600000000000186, 3.9830508474576263),
        (-0.858666666666668, 4.0395480225988685),
        (-1.5626666666666686, 3.926553672316384),
        (-2.2666666666666693, 3.5875706214689274),
        (-2.9413333333333362, 3.192090395480225),
        (-3.5280000000000022, 2.6553672316384187),
        (-3.909333333333336, 2.033898305084744),
        (-4.29066666666667, 1.3276836158192076),
        (-4.584000000000003, 0.6214689265536713),
        (-4.760000000000003, -0.11299435028248794),
        (-4.906666666666668, -0.9322033898305087),
        (-4.965333333333335, -1.6666666666666714),
        (-4.994666666666669, -2.344632768361585),
        (-4.8480000000000025, -3.2203389830508478),
        (-4.672000000000002, -3.8983050847457648),
        (-4.320000000000004, -4.576271186440678),
        (-3.8800000000000026, -5.225988700564974),
        (-3.4106666666666694, -5.734463276836161),
        (-2.765333333333336, -6.158192090395483),
        (-2.032000000000002, -6.610169491525427),
        (-1.3866666666666685, -6.920903954802263),
        (-0.6826666666666696, -7.06214689265537),
        (0.05066666666666464, -7.25988700564972),
        (0.8719999999999999, -7.401129943502829),
        (1.575999999999997, -7.372881355932208),
        (2.2799999999999976, -7.316384180790964),
    ),
    "Norma": (
        (-3.14666666666667, 0.8474576271186436),
        (-3.3226666666666684, 0.1977401129943459),
        (-3.2933333333333366, -0.7627118644067821),
        (-3.2346666666666692, -1.4406779661016955),
        (-2.970666666666668, -2.1186440677966125),
        (-2.5600000000000023, -2.824858757062149),
        (-2.1200000000000028, -3.4463276836158236),
        (-1.6506666666666696, -3.9548022598870105),
        (-0.9760000000000026, -4.378531073446332),
        (-0.2720000000000038, -4.689265536723166),
        (0.4319999999999986, -4.858757062146896),
        (0.9600000000000009, -4.887005649717519),
        (1.370666666666665, -4.858757062146896),
        (2.0453333333333283, -4.717514124293789),
        (2.6613333333333316, -4.519774011299436),
        (3.042666666666662, -4.406779661016952),
        (3.4826666666666632, -4.152542372881356),
        (4.010666666666662, -3.7288135593220346),
        (4.538666666666664, -3.050847457627121),
    ),
}
