import re
from pathlib import Path

import numpy as np

from ..variables import fpars_headers, fpars_order, plots_folder, root_ucc_path

header = """---
layout: layout_cluster
style: style_cluster
title: {cl_name}
title_flag: true
more_names: {more_names}
fname: {fname}
members_file: "{members_file}"
fov: {fov}
ra_icrs: {ra_icrs}
de_icrs: {de_icrs}
glon: {glon}
glat: {glat}
r50: {r50}
plx: {plx}
UTI: "{UTI}"
UTI_COLOR: "{UTI_COLOR}"
UTI_C_N_COL: "{UTI_C_N_COL}"
UTI_C_dens_COL: "{UTI_C_dens_COL}"
UTI_C_C3_COL: "{UTI_C_C3_COL}"
UTI_C_lit_COL: "{UTI_C_lit_COL}"
UTI_C_dup_COL: "{UTI_C_dup_COL}"
UTI_C_N: {UTI_C_N}
UTI_C_dens: {UTI_C_dens}
UTI_C_C3: {UTI_C_C3}
UTI_C_lit: {UTI_C_lit}
UTI_C_dup: {UTI_C_dup}
UTI_C_N_desc: {UTI_C_N_desc}
UTI_C_dens_desc: {UTI_C_dens_desc}
UTI_C_C3_desc: {UTI_C_C3_desc}
UTI_C_lit_desc: {UTI_C_lit_desc}
UTI_C_dup_desc: {UTI_C_dup_desc}
summary: |
{summary}
badge_dist: "{badge_dist}"
badge_dist_url: "{badge_dist_url}"
badge_av: "{badge_av}"
badge_av_url: "{badge_av_url}"
badge_mass: "{badge_mass}"
badge_mass_url: "{badge_mass_url}"
badge_feh: "{badge_feh}"
badge_feh_url: "{badge_feh_url}"
badge_age: "{badge_age}"
badge_age_url: "{badge_age_url}"
badge_bss: "{badge_bss}"
badge_bss_url: "{badge_bss_url}"
badge_nofpars_url: "{badge_nofpars_url}"
comments: |
{comments}
class3: |
{class3}
N_comments: "{N_comments}"
rc_val: {rc_val}
dens_val: {dens_val}
N_membs_val: {N_membs_val}
scix_url: {scix_url}
posit_table: |
{posit_table}
N_rows_pos: "{N_rows_pos}"
cds_radec: {cds_radec}
carousel: {carousel}
fpars_table: |
{fpars_table}
N_rows_pars: "{N_rows_pars}"
note_asterisk: {note_asterisk}
shared_table: |
{shared_table}
N_rows_shared: "{N_rows_shared}"
---
"""


def make(
    fname0,
    i_ucc,
    current_JSON,
    members_files_mapping,
    DBs_full_data,
    df_BC,
    UCC_cl,
    fnames_all,
    UTI_colors,
    summary,
    descriptors,
    fpars_badges,
    badges_url,
    comments_lst,
    tsp="    ",
):
    """
    Generate the content of a cluster entry page for the UCC. This is stored
    as a markdown file (.md) in the appropriate directory.

    The final .html is generated by the Jekyll engine when the website is built
    using the `layout_cluster.html'  layout.

    tsp: table spacing, added to the header to properly render tables and summary in
    .md files
    """

    cl_names = UCC_cl["Names"].split(";")

    more_names = ""
    if len(cl_names) > 1:
        more_names = " • ".join(cl_names[1:])

    members_file = members_files_mapping[fname0]

    # Generate fundamental parameters table
    fpars_table, N_rows_pars, mult_vals_note_flag = fpars_in_lit(
        current_JSON, UCC_cl, tsp
    )

    # summary = UCC_summ_cmmts[fname0]["summary"]
    UTI_C_N_desc, UTI_C_dens_desc, UTI_C_C3_desc, UTI_C_lit_desc, UTI_C_dup_desc = (
        descriptors
    )

    # Badges
    badges_names = ("dist", "av", "mass", "feh", "age", "bss")
    badge_dist, badge_av, badge_mass, badge_feh, badge_age, badge_bss = [
        fpars_badges.get(k, "") for k in badges_names
    ]

    def make_url(key):
        if not (val := badges_url.get(key)):
            return ""
        vmin, vmax = val
        return f"{key}_min={vmin}&{key}_max={vmax}"

    (
        badge_dist_url,
        badge_av_url,
        badge_mass_url,
        badge_feh_url,
        badge_age_url,
        badge_bss_url,
    ) = [make_url(k) for k in badges_names]

    # No fpars badge
    badge_nofpars_url = ""
    if all(
        b == ""
        for b in [badge_dist, badge_av, badge_mass, badge_feh, badge_age, badge_bss]
    ):
        # vmin = "1e6"
        vmax = "-99"
        badge_nofpars_url = f"dav_max={vmax}&bf_max={vmax}&"
        badge_nofpars_url += "&".join([f"{k}_max={vmax}" for k in badges_names])
        badge_nofpars_url += "&nofpars=true"

    # Comments
    comments, N_comments = "", ""
    if comments_lst:
        N_comments = 0
        for cmmt in comments_lst:
            comments += (
                f"{tsp}<p><u><a href='{cmmt['url']}' target='_blank'>"
                f"{cmmt['name']} ({cmmt['year']})</a></u>"
            )

            for i, comment in enumerate(cmmt["comment"]):
                name_used_db = ""
                if len(cl_names) > 1:  # and cmmt["orig_name"][i] != cl_names[0]:
                    name_used_db = f"<b>[{cmmt['orig_name'][i]}]</b> "
                comments += f"<br>{name_used_db}{comment}"

            comments += "</p>\n"
            N_comments += 1

    # Get colors used by the 'CX' classification
    abcd_c = tsp + color_C3(UCC_cl["C3"])

    cds_dec = (
        "+" + str(UCC_cl["DE_ICRS_m"])
        if UCC_cl["DE_ICRS_m"] >= 0
        else str(UCC_cl["DE_ICRS_m"])
    )
    cds_radec = f"{UCC_cl['RA_ICRS_m']},{cds_dec}"

    # Generate table with positional data: (ra, dec, plx, pmra, pmde, Rv)
    posit_table, N_rows_pos = positions_in_lit(current_JSON, DBs_full_data, UCC_cl, tsp)

    # Check present plots. The order here determines the order in which plots will be
    # shown: UCC --> HUNT23 --> CANTAT20
    carousel = "UCC"
    for _db in ("HUNT23", "CANTAT20"):
        plot_fpath = Path(
            root_ucc_path
            + plots_folder
            + f"plots_{fname0[0]}/"
            + _db
            + "/"
            + fname0
            + ".webp"
        )
        if plot_fpath.is_file() is True:
            carousel += "_" + _db

    # Generate table with OCs that share members with this one
    shared_table, N_rows_shared = table_shared_members(df_BC, fnames_all, UCC_cl, tsp)

    # Core radius (in pc)
    val = UCC_cl["r_core_pc"]
    r_core = (
        f"{val:.2f}"
        if val < 0.1
        else f"{round(val, 1):.1f}"
        if val < 10
        else f"{val:.0f}"
    )
    # Core density (in pc^-2)
    val = UCC_cl["dens_core_pc2"]
    dens_core = (
        f"{val:.2f}"
        if val < 0.1
        else f"{round(val, 1):.1f}"
        if val < 10
        else f"{val:.0f}"
    )

    contents = header.format(
        cl_name=cl_names[0],
        more_names=more_names,
        fname=fname0,
        members_file=members_file,
        fov=str(round(2 * (UCC_cl["r_50"] / 60.0), 3)),
        ra_icrs=str(UCC_cl["RA_ICRS_m"]),
        de_icrs=str(UCC_cl["DE_ICRS_m"]),
        glon=str(UCC_cl["GLON_m"]),
        glat=str(UCC_cl["GLAT_m"]),
        r50=str(UCC_cl["r_50"]),
        plx=str(UCC_cl["Plx_m"]),
        UTI="1.0" if UCC_cl["UTI"] == 1.0 else f"{UCC_cl['UTI']:.2f}",
        UTI_COLOR=UTI_colors["UTI"][i_ucc],
        UTI_C_N_COL=UTI_colors["C_N"][i_ucc],
        UTI_C_dens_COL=UTI_colors["C_dens"][i_ucc],
        UTI_C_C3_COL=UTI_colors["C_C3"][i_ucc],
        UTI_C_lit_COL=UTI_colors["C_lit"][i_ucc],
        UTI_C_dup_COL=UTI_colors["C_dup"][i_ucc],
        UTI_C_N=str(UCC_cl["C_N"]),
        UTI_C_dens=str(UCC_cl["C_dens"]),
        UTI_C_C3=str(UCC_cl["C_C3"]),
        UTI_C_lit=str(UCC_cl["C_lit"]),
        UTI_C_dup=str(UCC_cl["C_dup"]),
        UTI_C_N_desc=UTI_C_N_desc,
        UTI_C_dens_desc=UTI_C_dens_desc,
        UTI_C_C3_desc=UTI_C_C3_desc,
        UTI_C_lit_desc=UTI_C_lit_desc,
        UTI_C_dup_desc=UTI_C_dup_desc,
        summary=summary,
        badge_dist=badge_dist,
        badge_dist_url=badge_dist_url,
        badge_av=badge_av,
        badge_av_url=badge_av_url,
        badge_mass=badge_mass,
        badge_mass_url=badge_mass_url,
        badge_feh=badge_feh,
        badge_feh_url=badge_feh_url,
        badge_age=badge_age,
        badge_age_url=badge_age_url,
        badge_bss=badge_bss,
        badge_bss_url=badge_bss_url,
        badge_nofpars_url=badge_nofpars_url,
        comments=comments,
        N_comments=N_comments,
        class3=abcd_c,
        rc_val=r_core,
        dens_val=dens_core,
        N_membs_val=str(int(UCC_cl["N_membs"])),
        scix_url=cl_names[0].replace(" ", "%20"),
        posit_table=posit_table,
        N_rows_pos=N_rows_pos,
        cds_radec=cds_radec,
        carousel=carousel,
        fpars_table=fpars_table,
        N_rows_pars=N_rows_pars,
        note_asterisk=mult_vals_note_flag,
        shared_table=shared_table,
        N_rows_shared=N_rows_shared,
    )

    return contents


def positions_in_lit(DBs_json, DBs_full_data, UCC_cl, tsp):
    """
    Generate a markdown table with positional data (RA, DEC, Plx, pmRA, pmDE, Rv) from
    """
    DBs_sort = UCC_cl["DB"].split(";")[::-1]
    DBs_i_sort = UCC_cl["DB_i"].split(";")[::-1]
    F_scores = UCC_cl["F_score"].split(";")[::-1]

    table = (
        f"{tsp}| Reference | Year | F<sub>s</sub> | RA [deg] | DEC [deg] | Plx [mas] | pmRA [mas/yr] | pmDE [mas/yr] | Rv [km/s] |\n"
        + "    | :--- | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |\n"
    )

    # Add UCC positions
    # table += f"{tsp}| **UCC** |" + '<span class="hidden-cell-val">99999</span>' + "-- |" + " -- |"
    table += f'{tsp}| **UCC** |<span class="hidden-cell-val">99999</span>-- | -- |'
    for col in ("RA_ICRS_m", "DE_ICRS_m", "Plx_m", "pmRA_m", "pmDE_m", "Rv_m"):
        val = "--"
        if UCC_cl[col] != "" and not np.isnan(UCC_cl[col]):
            val = str(round(float(UCC_cl[col]), 3))
        table += val + " | "
    table = table[:-1] + "\n"

    N_rows = 0
    for i, db in enumerate(DBs_sort):
        # Full 'db' database
        df = DBs_full_data[db]

        # Add positions
        row_in = ""
        for c in ("RA", "DEC", "plx", "pmra", "pmde", "Rv"):
            if c in DBs_json[db]["pos"]:
                df_col_name = DBs_json[db]["pos"][c]
                # Read position as string
                pos_v = str(df[df_col_name][int(DBs_i_sort[i])])
                # Remove empty spaces if any
                pos_v = pos_v.replace(" ", "")
                if pos_v != "" and pos_v != "nan":
                    row_in += str(round(float(pos_v), 3)) + " | "
                else:
                    row_in += "-- | "
            else:
                row_in += "-- | "

        # See if the row contains any values
        if row_in.replace("--", "").replace("|", "").strip() != "":
            # Add reference
            ref_url = f"[{DBs_json[db]['authors']}]({DBs_json[db]['SCIX_url']})"
            year = DBs_json[db]["year"]
            # The spaces at the beginning is to add proper spacing to the final .md file
            table += tsp + "|" + ref_url + " | " + year + " | " + F_scores[i] + " | "
            # Close and add row
            table += row_in[:-1] + "\n"
            N_rows += 1

    # Remove the last two characters (newline and space)
    table = table[:-2]

    return table, N_rows


def eq_positions_in_lit(DBs_json, DBs_full_data, UCC_cl) -> list:
    """
    Return the (reference, RA, DEC) values for each DB that lists this cluster,
    in the same order used by the 'Astrometry' table (see 'positions_in_lit').
    """
    DBs_sort = UCC_cl["DB"].split(";")[::-1]
    DBs_i_sort = UCC_cl["DB_i"].split(";")[::-1]

    refs = []
    for i, db in enumerate(DBs_sort):
        db_pos = DBs_json[db]["pos"]
        if "RA" not in db_pos or "DEC" not in db_pos:
            continue
        df = DBs_full_data[db]

        radec = []
        for c in ("RA", "DEC"):
            pos_v = str(df[db_pos[c]][int(DBs_i_sort[i])]).replace(" ", "")
            if pos_v == "" or pos_v == "nan":
                break
            radec.append(round(float(pos_v), 3))
        else:
            ref = f"{DBs_json[db]['authors']} {DBs_json[db]['year']}"
            refs.append([ref, radec[0], radec[1]])

    return refs


def fpars_in_lit(
    DBs_json: dict,
    UCC_cl: dict,
    tsp: str,
):
    """
    DBs_json: JSON that contains the data for all DBs
    DBs_full_data: dictionary of pandas.DataFrame for all DBs
    DBs: DBs where this cluster is present
    DBs_i: Indexes where this cluster is present in each DB
    """

    mult_vals_note_flag = "false"

    F_scores = UCC_cl["F_score"].split(";")

    # Reverse years order to show the most recent first
    DBs_lst = UCC_cl["DB"].split(";")[::-1]
    F_scores = F_scores[::-1]
    par_dict = {}
    for par in fpars_order:
        par_dict[par] = str(UCC_cl[par]).split(";")[::-1]

    rows, N_rows_pars = [], 0
    for i, db in enumerate(DBs_lst):
        row = [f"[{DBs_json[db]['authors']}]({DBs_json[db]['SCIX_url']})"]
        row.append(DBs_json[db]["year"])
        row.append(F_scores[i])

        for par in fpars_order:
            par_v = "--" if par_dict[par][i] == "nan" else par_dict[par][i]
            if "*" in par_v:
                mult_vals_note_flag = "true"
                par_v = re.sub(r"\*+", f"<sup>({par_v.count('*')})</sup>", par_v)
            row.append(par_v)
        # Filter rows where all columns after the F_score are '--'
        if not all(v == "--" for v in row[3:]):
            rows.append(row)
            N_rows_pars += 1

    if not rows:
        # Return empty values
        return "", "", mult_vals_note_flag

    def md_row(row):
        return "| " + " | ".join(row) + " |"

    # Properly format UCC median values
    medians = []
    for par in fpars_order:
        val = UCC_cl[par + "_median"]
        if str(val) == "nan":
            medians.append("--")
        else:
            if par in ("age", "mass"):
                medians.append(f"{val:.0f}")
            elif par == "blue_str":
                if val > 0 and val < 1:
                    # Handle fractional values
                    medians.append(f"{val:.3f}")
                else:
                    medians.append(f"{val:.0f}")
            elif par == "met":
                medians.append(f"{val:.3f}")
            else:
                medians.append(f"{val}")

    UCC_medians = [
        "**UCC**",
        '<span class="hidden-cell-val">99999</span>' + "--",
        "--",  # F_score
    ] + medians
    rows = [UCC_medians] + rows

    align = [":---"] + [":---:"] * (len(fpars_headers) - 1)
    table = [
        md_row(fpars_headers),
        "| " + " | ".join(align) + " |",
        *(md_row(r) for r in rows),
    ]
    table = "\n".join(tsp + line for line in table)

    return table, N_rows_pars, mult_vals_note_flag


def color_C3(abcd):
    """
    Return a string with HTML span elements for each letter in 'abcd', colored
    according to a predefined mapping.
    """
    abcd_c = ""
    line = r"""<span style="color: {}; font-weight: bold;">{}</span>"""
    cc = {"A": "green", "B": "#FFC300", "C": "red", "D": "purple"}
    for letter in abcd:
        abcd_c += line.format(cc[letter], letter)  # + '\n'
    return abcd_c


def table_shared_members(df_UCC, fnames_all, row, tsp):
    """
    Generate a markdown table with OCs that share members with the given OC.
    """
    shared_members_tab = ""

    if str(row["shared_members"]) == "nan":
        return shared_members_tab, 0

    shared_members_tab = (
        tsp
        + """| Cluster | <span title="Percentage of members that this OC shares with the ones listed">%</span>   | RA   | DEC   | Plx   | pmRA  | pmDE  | Rv | UTI |\n"""
    )
    shared_members_tab += (
        tsp + "| :-: | :-: |:-: | :-: | :-: | :-: | :-: | :-: | :-: |\n"
    )

    shared_fnames = row["shared_members"].split(";")
    shared_percents = row["shared_members_p"].split(";")
    N_rows_shared = len(shared_fnames)

    for i, fname in enumerate(shared_fnames):
        # Locate OC with shared members in the UCC
        j = fnames_all.index(fname)

        name = df_UCC["Names"][j].split(";")[0]
        vals = []
        for col in (
            "RA_ICRS_m",
            "DE_ICRS_m",
            "Plx_m",
            "pmRA_m",
            "pmDE_m",
            "Rv_m",
            "UTI",
        ):
            val = round(float(df_UCC[col][j]), 2)
            if np.isnan(val):
                vals.append("--")
            else:
                vals.append(val)
        val = shared_percents[i]
        if val == "nan":
            vals.append("--")
        else:
            vals.append(val)

        ra, dec, plx, pmRA, pmDE, Rv, UTI, perc = vals

        shared_members_tab += f"{tsp}|[{name}](/_clusters/{fname}/)| "
        shared_members_tab += f"{perc} | "
        shared_members_tab += f"{ra} | "
        shared_members_tab += f"{dec} | "
        shared_members_tab += f"{plx} | "
        shared_members_tab += f"{pmRA} | "
        shared_members_tab += f"{pmDE} | "
        shared_members_tab += f"{Rv} |"
        shared_members_tab += f"{UTI} |\n"

    # Remove final new line
    shared_members_tab = shared_members_tab[:-1]

    return shared_members_tab, N_rows_shared
